name: DB Migration
run-name: DB Migration for ${{ inputs.tag || github.head_ref }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Branch/tag/hash to test"
        required: true
        default: "migration-plan-gha"
      env:
        description: "Environment to run the migration against"
        required: true
        type: choice
        options:
          - "dev"
          - "qa"
          - "prod"
      command:
        description: "Migration command to run"
        required: true
        type: choice
        options:
          - "verify"
          - "create"
          - "list"
          - "profiles"
          - "rollback"
      batch_id:
        description: "Batch ID for migration"
        required: true
      batch_name:
        description: "Batch Name for migration - needed for create command"
        required: false
      client_name:
        description: "Client Name - needed for create command"
        required: false
      percentage:
        description: "Percentage of total records - needed for create command"
        required: false

jobs:
  run_db_migration:
    name: DB Migration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run DB Migration Script
      run: |
        echo "Running db migration with command ${{ inputs.command }} on environment ${{ inputs.env }}"
        npm run migrate:batch:${{ inputs.command }}