name: DB Migration
run-name: DB Migration for ${{ inputs.tag || github.head_ref }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Branch/tag/hash to test"
        required: true
        default: "migration-plan-gha"
      env:
        description: "Environment to run the migration"
        required: true
        type: choice
        options:
          - "dev"
          - "qa"
          - "prod"
      command:
        description: "Migration command to run"
        required: true
        type: choice
        options:
          - "create"
          - "verify"
          - "profiles"
          - "rollback"
          - "list"
      batch_id:
        description: "Batch ID for migration"
        required: true
      batch_name:
        description: "Batch Name for migration"
        required: false
      client_name:
        description: "Client Name"
        required: false
      percentage:
        description: "Percentage of total records to migrate"
        required: false

jobs:
  run_db_migration:
    name: DB Migration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run DB Migration Script
      run: |
        echo "Running db migration with command ${{ inputs.command }} on environment ${{ inputs.env }}"
        # npm run migrate:batch:${{ inputs.command }}
        if: ${{ inputs.command == 'verify' }}; then
          npm run migrate:batch:create -- --env=${{ inputs.env }} --batchId=${{ inputs.batch_id }}
        else if: ${{ inputs.command == 'create' }}; then
          npm run migrate:batch:create -- --env=${{ inputs.env }} --name="${{ inputs.batch_name }}" --clientName="${{ inputs.client_name }}" --percentage=${{ inputs.percentage }}
        else if: ${{ inputs.command == 'profiles' }}; then
          npm run migrate:batch:profiles -- --env=${{ inputs.env }} --batchId=${{ inputs.batch_id }} --preCheck=true
        else if: ${{ inputs.command == 'migrate' }}; then
          npm run migrate:batch:migrate -- --env=${{ inputs.env }} --batchId=${{ inputs.batch_id }}
        fi